/**
 * Système d'émotions — 9 états + phonèmes/visèmes
 * Design minimaliste, géométrique, anti-vallée de l'étrange.
 */

export const EMOTIONS = {
  neutral: {
    label: 'Neutre',
    color: '#FF9F1C',
    eyeOpenness: 1.0,
    eyeGlow:     0.45,
    browAngle:   0,
    mouthCurve:  0,
    mouthOpen:   0.04,
    glowIntensity: 0.35,
    blinkRate:   4200,
    ambientPulse: false,
    pupilOffset: { x: 0, y: 0 },
  },
  happy: {
    label: 'Joyeux',
    color: '#F6C453',
    eyeOpenness: 1.18,
    eyeGlow:     0.88,
    browAngle:   7,
    mouthCurve:  11,
    mouthOpen:   0.28,
    glowIntensity: 0.8,
    blinkRate:   4800,
    ambientPulse: true,
    pupilOffset: { x: 0, y: -1 },
  },
  curious: {
    label: 'Curieux',
    color: '#3CCFCF',
    eyeOpenness: 1.22,
    eyeGlow:     0.7,
    browAngle:   9,
    mouthCurve:  3,
    mouthOpen:   0.1,
    glowIntensity: 0.6,
    blinkRate:   3600,
    ambientPulse: false,
    pupilOffset: { x: 3, y: -2 },
  },
  listening: {
    label: 'Écoute',
    color: '#60A5FA',
    eyeOpenness: 1.06,
    eyeGlow:     0.6,
    browAngle:   4,
    mouthCurve:  1,
    mouthOpen:   0.05,
    glowIntensity: 0.5,
    blinkRate:   3100,
    ambientPulse: false,
    pupilOffset: { x: 0, y: 0 },
  },
  thinking: {
    label: 'Réflexion',
    color: '#FF9F1C',
    eyeOpenness: 0.82,
    eyeGlow:     0.38,
    browAngle:   -4,
    mouthCurve:  -2,
    mouthOpen:   0.04,
    glowIntensity: 0.28,
    blinkRate:   5500,
    ambientPulse: true,
    pupilOffset: { x: -4, y: 2 },
  },
  excited: {
    label: 'Excité',
    color: '#F6C453',
    eyeOpenness: 1.35,
    eyeGlow:     1.0,
    browAngle:   14,
    mouthCurve:  14,
    mouthOpen:   0.52,
    glowIntensity: 1.0,
    blinkRate:   3000,
    ambientPulse: true,
    pupilOffset: { x: 0, y: -2 },
  },
  sleepy: {
    label: 'Somnolent',
    color: '#5B2C1F',
    eyeOpenness: 0.38,
    eyeGlow:     0.18,
    browAngle:   -1,
    mouthCurve:  -3,
    mouthOpen:   0.04,
    glowIntensity: 0.15,
    blinkRate:   1800,
    ambientPulse: false,
    pupilOffset: { x: 0, y: 3 },
  },
  sad: {
    label: 'Triste',
    color: '#60A5FA',
    eyeOpenness: 0.72,
    eyeGlow:     0.28,
    browAngle:   5,
    mouthCurve:  -9,
    mouthOpen:   0.06,
    glowIntensity: 0.32,
    blinkRate:   2400,
    ambientPulse: false,
    pupilOffset: { x: 0, y: 2 },
  },
  alert: {
    label: 'Alerte',
    color: '#FF5A5F',
    eyeOpenness: 1.42,
    eyeGlow:     0.92,
    browAngle:   -9,
    mouthCurve:  0,
    mouthOpen:   0.06,
    glowIntensity: 0.88,
    blinkRate:   6500,
    ambientPulse: true,
    pupilOffset: { x: 0, y: -1 },
  },
}

/** Phonème → shape de bouche (visème simplifié) */
export const VISEMES = {
  rest: { open: 0.04, wide: 1.0,  round: 0 },
  A:    { open: 0.75, wide: 1.08, round: 0 },
  E:    { open: 0.42, wide: 1.24, round: 0 },
  I:    { open: 0.24, wide: 1.32, round: 0 },
  O:    { open: 0.68, wide: 0.84, round: 1 },
  U:    { open: 0.38, wide: 0.74, round: 1 },
  M:    { open: 0.0,  wide: 1.0,  round: 0 },
  F:    { open: 0.18, wide: 1.04, round: 0 },
  S:    { open: 0.14, wide: 1.1,  round: 0 },
  TH:   { open: 0.20, wide: 1.0,  round: 0 },
}

export const EMOTION_ORDER = [
  'neutral','happy','curious','listening',
  'thinking','excited','sleepy','sad','alert',
]
